# aliases — sourced by .bashrc
# macOS · DevOps + Data Engineering/Science

# Navigation
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias ~='cd ~'

# Listing
alias ls='ls -G'
alias ll='ls -AlhiF'
alias l='ls -A'
alias la='ls -A'

# General
alias c='clear'
alias b='btop'
alias reload='exec $SHELL -l'
alias path='echo $PATH | tr ":" "\n"'
alias pubip='curl -s https://ipwho.is/ | jq .'
alias privip="ifconfig | grep 'inet ' | grep -v '127.0.0.1' | awk '{print \$2}'"
alias pubkey='cat ~/.ssh/id_rsa.pub'
alias pubkeys='ls ~/.ssh/*.pub 2>/dev/null | xargs -I{} sh -c "echo \"=== {} ===\"; cat {}"'
alias password='openssl rand -base64 48'

# Editors
alias nano='vim'

# macOS clipboard
alias copy='pbcopy'
alias paste='pbpaste'

# Homebrew
alias brewup='brew update && brew upgrade && brew upgrade --cask && brew cleanup && brew doctor'
alias brewls='brew list'
alias brewi='brew install'
alias brewinfo='brew info'

# Git
alias g='git'
alias gs='git status'
alias ga='git add'
alias gaa='git add --all'
alias gc='git commit -m'
alias gca='git commit --amend --no-edit'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gb='git branch'
alias gba='git branch -a'
alias gbd='git branch -d'
alias gbD='git branch -D'
alias gl='git log --oneline --graph --decorate --all'
alias gll='git log --stat'
alias gd='git diff'
alias gds='git diff --staged'
alias gp='git push'
alias gpf='git push --force-with-lease'
alias gpl='git pull'
alias gpr='git pull --rebase'
alias gst='git stash'
alias gstp='git stash pop'
alias gstl='git stash list'
alias gf='git fetch --all --prune'
alias grb='git rebase'
alias grbi='git rebase -i'
alias gcp='git cherry-pick'
alias gtag='git tag'
alias gclean='git clean -fd'
alias gwip='git add -A && git commit -m "wip: checkpoint"'

# Python / venv
alias py='python3'
alias pip='pip3'
alias piv='python3 -m venv .venv'
alias va='source .venv/bin/activate'
alias vd='deactivate'
alias pipi='pip3 install'
alias pipu='pip3 install --upgrade'
alias pipf='pip3 freeze'
alias pipff='pip3 freeze > requirements.txt'
alias pipr='pip3 install -r requirements.txt'
alias pipuu='pip3 list --outdated | awk "NR>2 {print \$1}" | xargs pip3 install --upgrade'

# Jupyter
alias jn='jupyter notebook'
alias jl='jupyter lab'
alias jnb='jupyter nbconvert'

# Docker
alias d='docker'
alias dps='docker ps'
alias dpsa='docker ps -a'
alias di='docker images'
alias drm='docker rm'
alias drmi='docker rmi'
alias drmf='docker rm -f'
alias dex='docker exec -it'
alias dlogs='docker logs -f'
alias dstop='docker stop'
alias dstart='docker start'
alias dprune='docker system prune -af --volumes'
alias dc='docker compose'
alias dcu='docker compose up -d'
alias dcd='docker compose down'
alias dcl='docker compose logs -f'
alias dcr='docker compose restart'
alias dcb='docker compose build'

# Kubernetes
alias k='kubectl'
alias kgp='kubectl get pods'
alias kgpa='kubectl get pods --all-namespaces'
alias kgs='kubectl get services'
alias kgn='kubectl get nodes'
alias kgd='kubectl get deployments'
alias kdes='kubectl describe'
alias kdp='kubectl describe pod'
alias kds='kubectl describe service'
alias kdn='kubectl describe node'
alias klogs='kubectl logs -f'
alias kex='kubectl exec -it'
alias kap='kubectl apply -f'
alias kdel='kubectl delete -f'
alias kctx='kubectl config get-contexts'
alias kuse='kubectl config use-context'
alias kns='kubectl config set-context --current --namespace'
alias krun='kubectl run --rm -it --image=busybox debug -- sh'

# Network
alias ports='lsof -i -P -n | grep LISTEN'
alias flush-dns='sudo dscacheutil -flushcache && sudo killall -HUP mDNSResponder'

# Filesystem / safety
alias cp='cp -iv'
alias mv='mv -iv'
alias mkdir='mkdir -pv'
alias df='df -h'
alias du='du -sh'
alias dud='du -sh -- *'

# Directory stack
alias pd='pushd'
alias pp='popd'
alias ds='dirs -v'

# Find
alias fd='find . -type d -name'
alias ff='find . -type f -name'

# Size and tree
alias dsize='du -sh -- */ | sort -h'
alias count='ls -1 | wc -l'
alias t2='tree -L 2'
alias t3='tree -L 3'
alias th='tree -L 2 -a -I ".git|.venv|__pycache__|node_modules|*.pyc"'
